# Shell variables
# Generated by 'wal'
wallpaper='/home/elijah/.config/backgrounds/black-hole.jpg'

# Special
background='#09080F'
foreground='#f1c4c5'
cursor='#f1c4c5'

# Colors
color0='#09080F'
color1='#6D385B'
color2='#6E3D5D'
color3='#9F4C6E'
color4='#C15672'
color5='#B46885'
color6='#E87287'
color7='#f1c4c5'
color8='#a88989'
color9='#6D385B'
color10='#6E3D5D'
color11='#9F4C6E'
color12='#C15672'
color13='#B46885'
color14='#E87287'
color15='#f1c4c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
