--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="$HOME/.config/backgrounds/black-hole.jpg"

-- Special
background="#09080F"
foreground="#f1c4c5"
cursor="#f1c4c5"

-- Colors
color0="#09080F"
color1="#6D385B"
color2="#6E3D5D"
color3="#9F4C6E"
color4="#C15672"
color5="#B46885"
color6="#E87287"
color7="#f1c4c5"
color8="#a88989"
color9="#6D385B"
color10="#6E3D5D"
color11="#9F4C6E"
color12="#C15672"
color13="#B46885"
color14="#E87287"
color15="#f1c4c5"
